import type { LayerData, SemanticId } from "./types.ts";
import type { TextLayout } from "./editable-text.ts";
export type ShapeKind = "rect" | "ellipse" | "line" | "icon" | "triangle" | "polygon" | "star" | "diamond";
export type ShapeSpec = { kind: ShapeKind; fill: string; stroke: string; strokeWidth: number; radius?: number; icon?: string; sides?: number; gradient?: { axis: "horizontal" | "vertical"; from: string; to: string }; softness?: number };

export type TextFx = { gradient?: [string, string] | null; strokeColor?: string; strokeW?: number; shadow?: boolean; italic?: boolean; letterSpacing?: number;
  warp?: "none" | "arc-up" | "arc-down" | "wave"; warpAmount?: number; waveCount?: number };
export type SavedLayer = {
  id: string; name: string; type: LayerData["type"]; zIndex: number;
  x: number; y: number; w: number; h: number; rotation: number; visible: boolean; opacity: number; locked: boolean;
  image?: string;                     // image layers: persistent URL (or data: fallback)
  isArt?: boolean;                    // image layer generated by AI 文字藝術字（可再 AI 微調）
  artRefImage?: string;               // 生成時用的風格參考圖（data URL）
  isText?: boolean; text?: string; color?: string; fontSize?: number; fontFamily?: string; fontWeight?: number; align?: "left" | "center" | "right";
  fx?: TextFx | null;
  textLayout?: TextLayout;
  shape?: { kind: ShapeKind; fill: string; stroke: string; strokeWidth: number; radius?: number; icon?: string; sides?: number; gradient?: { axis: "horizontal" | "vertical"; from: string; to: string }; softness?: number };
  groupId?: string | null;
};
export function savedToLayerData(sl: SavedLayer): LayerData {
  const semanticId: SemanticId = sl.type === "independent_text" ? "text" : (sl.type as SemanticId);
  return {
    id: sl.id, type: sl.type, name: sl.name, semanticId, instanceId: sl.id, parentId: null,
    bbox: { x: sl.x, y: sl.y, w: sl.w, h: sl.h }, mask: null,
    image: sl.isText ? null : (sl.image ?? null),
    x: sl.x, y: sl.y, width: sl.w, height: sl.h, rotation: sl.rotation,
    zIndex: sl.zIndex, confidence: 1, source: "generated", editable: true,
    embeddedText: [], children: [],
    meta: {
      visible: sl.visible, locked: sl.locked, opacity: sl.opacity, groupId: sl.groupId ?? null,
      ...(sl.isText ? { style: { text: sl.text, fontSizePx: sl.fontSize, fontWeight: sl.fontWeight, color: sl.color, align: sl.align, fontFamily: sl.fontFamily, fx: sl.fx ?? null, ...(sl.textLayout ? { layout: sl.textLayout } : {}) }, textObject: { text: sl.text } } : {}),
      ...(sl.isArt ? { isArt: true, artText: sl.text ?? "", ...(sl.artRefImage ? { artRefImage: sl.artRefImage } : {}) } : {}),
      ...(sl.shape ? { shape: sl.shape } : {}),
    },
  };
}
