/**
 * Visual Templates — 資料（第一批 · 規劃層）
 * ─────────────────────────────────────────────────────────────────────────────
 * 這是「先驗證用」的第一批（涵蓋 A–K 各分類），schema 完整、設計語法真正不同。
 * 驗證流程通過後再量產到 80–100（目標）。每個 Template＝一整組共用的 Visual DNA。
 *
 * 不接生成、不動 Sharp/API/Prisma。品牌主色/產品/人物一致性仍走現有 lock。
 */
import type { VisualTemplate } from "@/lib/multi/visual-template-types";

export const VISUAL_TEMPLATES: VisualTemplate[] = [
  // ── A. Clean / Minimal ──────────────────────────────────────────
  {
    id: "clean-white-editorial", name: "Clean White Editorial", category: "clean_minimal",
    description: "大面積留白、乾淨無襯線、極少裝飾的純淨編輯風。",
    visualConcept: "Photo + clean typography，大量留白、低裝飾、克制。",
    colorSystem: { primary: "near-white / soft ink black", secondary: "light warm grey", accent: "single restrained brand accent", background: "pure clean white" },
    typography: { hierarchy: "one large headline, tiny caption", headlineStyle: "bold clean sans-serif, generous letter-spacing", bodyStyle: "light small sans-serif", labelStyle: "uppercase micro-label", alignment: "left-aligned, top-left anchor" },
    imageTreatment: { photographyStyle: "clean product/lifestyle photography", lighting: "soft even daylight", contrast: "medium-low", saturation: "natural, slightly muted", depthOfField: "moderate" },
    composition: { visualHierarchy: "image dominant, text minimal", readingDirection: "top-left to bottom", whitespace: "very high", balance: "calm asymmetry", imageScale: "large" },
    subjectTreatment: { people: "natural candid, uncluttered", product: "clean isolated on simple surface", environment: "minimal, airy" },
    textTreatment: { placement: "top-left headline, bottom-left caption", overlay: "none / on white margin", caption: "small muted", cardVariant: "title-top-caption-bottom" },
    decorativeElements: ["thin hairline rule"], shapeLanguage: "sharp / minimal rounding",
    consistencyRules: ["all frames pure white background", "same headline typeface & position logic", "same soft daylight"],
    recommendedFor: ["editorial", "product", "beauty", "wellness"], avoid: ["heavy gradients", "busy decoration"],
    frameRoles: { hero: "大留白主標＋主體", secondary: "產品/細節乾淨特寫", supporting: "情境小景", closing: "留白＋caption 收尾" },
  },
  {
    id: "soft-beige-minimal", name: "Soft Beige Minimal", category: "clean_minimal",
    description: "米色調、柔和自然、溫暖極簡。",
    visualConcept: "溫暖大地色的極簡，柔光、圓潤、療癒。",
    colorSystem: { primary: "warm beige / taupe", secondary: "cream", accent: "muted terracotta", background: "soft beige" },
    typography: { hierarchy: "medium headline, soft caption", headlineStyle: "rounded humanist sans", bodyStyle: "light serif or humanist", labelStyle: "small pill label", alignment: "center or left" },
    imageTreatment: { photographyStyle: "warm natural lifestyle", lighting: "warm soft window light", contrast: "low", saturation: "warm muted", grain: "subtle film grain" },
    composition: { visualHierarchy: "balanced image+text", readingDirection: "center-out", whitespace: "high", balance: "symmetric calm", imageScale: "medium-large" },
    subjectTreatment: { people: "relaxed, warm", product: "on natural textures (linen/wood)", environment: "cozy neutral home" },
    textTreatment: { placement: "top label, centered caption", overlay: "soft cream card", textBox: "rounded soft card", caption: "warm tone", cardVariant: "minimal-top-label-card" },
    decorativeElements: ["soft rounded card", "tiny botanical accent"], shapeLanguage: "very rounded",
    consistencyRules: ["same warm beige palette", "same soft grain", "same rounded card language"],
    recommendedFor: ["lifestyle", "beauty", "wellness", "food"], avoid: ["cold tones", "hard contrast"],
    frameRoles: { hero: "溫暖情境主圖", secondary: "產品置於自然材質", supporting: "質地/成分特寫", closing: "柔卡收尾" },
  },

  // ── B. Lifestyle / Human ────────────────────────────────────────
  {
    id: "japanese-lifestyle", name: "Japanese Clean Lifestyle", category: "lifestyle_human",
    description: "日系清新、乾淨明亮、自然生活感。",
    visualConcept: "日系雜誌感生活，明亮通透、簡潔留白、真實。",
    colorSystem: { primary: "bright neutral", secondary: "soft sky/green hint", accent: "muted brand color", background: "bright airy off-white" },
    typography: { hierarchy: "clean headline + fine caption", headlineStyle: "light-to-medium sans, airy", bodyStyle: "fine sans caption", labelStyle: "small pill", alignment: "left" },
    imageTreatment: { photographyStyle: "bright Japanese lifestyle", lighting: "bright diffused daylight", contrast: "medium-low", saturation: "fresh natural", depthOfField: "soft background" },
    composition: { visualHierarchy: "airy, breathable", readingDirection: "left to right", whitespace: "high", balance: "light asymmetry", imageScale: "large" },
    subjectTreatment: { people: "natural candid daily moment", product: "integrated into daily scene", environment: "bright tidy home / cafe" },
    textTreatment: { placement: "caption pill on photo", overlay: "subtle", badge: "small round pill", caption: "fine grey", cardVariant: "photo-caption-pill" },
    decorativeElements: ["small pill caption", "thin divider"], shapeLanguage: "gently rounded",
    consistencyRules: ["same bright airy tone across frames", "same fine caption pill", "same natural daylight"],
    recommendedFor: ["lifestyle", "beauty", "wellness", "product"], avoid: ["dark moody", "heavy saturation"],
    frameRoles: { hero: "明亮生活主圖", secondary: "產品日常特寫", supporting: "使用情境", closing: "清新收尾" },
  },
  {
    id: "natural-morning", name: "Natural Morning", category: "lifestyle_human",
    description: "晨光、自然、放鬆的一天開始。",
    visualConcept: "清晨柔光下的自然生活，溫柔、真實、有呼吸感。",
    colorSystem: { primary: "warm morning neutral", secondary: "pale gold", accent: "soft green", background: "sunlit cream" },
    typography: { hierarchy: "soft headline + caption", headlineStyle: "humanist serif/sans", bodyStyle: "light", labelStyle: "small", alignment: "left" },
    imageTreatment: { photographyStyle: "golden-hour lifestyle", lighting: "warm low morning sun, long soft shadows", contrast: "low-medium", saturation: "warm", grain: "light" },
    composition: { visualHierarchy: "atmosphere-led", readingDirection: "top-down", whitespace: "medium-high", balance: "organic", imageScale: "large" },
    subjectTreatment: { people: "calm morning routine", product: "on sunlit surface", environment: "bright bedroom/kitchen morning" },
    textTreatment: { placement: "bottom over gradient", overlay: "soft bottom gradient", gradient: "warm bottom fade", caption: "light", cardVariant: "gradient-bottom" },
    decorativeElements: ["sun-flare hint"], shapeLanguage: "rounded",
    consistencyRules: ["same golden morning light in every frame", "same warm palette", "same bottom-gradient text"],
    recommendedFor: ["lifestyle", "wellness", "beauty"], avoid: ["neon", "studio flat light"],
    frameRoles: { hero: "晨光人物情境", secondary: "產品沐光", supporting: "生活小景", closing: "溫暖收束" },
  },

  // ── C. Editorial / Magazine ─────────────────────────────────────
  {
    id: "asymmetric-editorial", name: "Asymmetric Editorial", category: "editorial_magazine",
    description: "不對稱構圖、大標、編號、雜誌藝術指導感。",
    visualConcept: "雜誌式不對稱排版，大膽留白＋精緻小字。",
    colorSystem: { primary: "ink black / paper white", secondary: "grey", accent: "one bold editorial color", background: "paper white" },
    typography: { hierarchy: "oversized headline vs tiny serif caption", headlineStyle: "oversized condensed / serif display", bodyStyle: "small serif", labelStyle: "numbered index (01/02)", alignment: "mixed, intentional off-grid" },
    imageTreatment: { photographyStyle: "editorial fashion/beauty", lighting: "directional, sculpted", contrast: "medium-high", saturation: "controlled" },
    composition: { visualHierarchy: "strong focal + generous void", readingDirection: "diagonal / off-grid", whitespace: "high", balance: "deliberate asymmetry", imageScale: "large hero, small details" },
    subjectTreatment: { people: "posed editorial", product: "sculptural placement", environment: "minimal set" },
    textTreatment: { placement: "corner label + big headline", overlay: "on margin", badge: "numbered corner label", caption: "tiny serif", cardVariant: "corner-label-card" },
    decorativeElements: ["frame numbering", "thin rule"], shapeLanguage: "sharp",
    consistencyRules: ["same numbering system across frames", "same serif caption", "same directional light"],
    recommendedFor: ["editorial", "fashion", "beauty", "launch"], avoid: ["rounded cute cards", "clutter"],
    frameRoles: { hero: "大標＋不對稱主圖", secondary: "編號細節", supporting: "留白小圖", closing: "收尾編號" },
  },
  {
    id: "fashion-editorial", name: "Fashion Editorial", category: "editorial_magazine",
    description: "時尚大片、全出血照片、頂部大標。",
    visualConcept: "時裝大片感，照片主導、字壓在照片上。",
    colorSystem: { primary: "high-contrast mono", secondary: "skin/neutral", accent: "sharp accent", background: "full-bleed photo" },
    typography: { hierarchy: "bold top headline over photo", headlineStyle: "condensed bold", bodyStyle: "minimal", labelStyle: "small caps", alignment: "top" },
    imageTreatment: { photographyStyle: "high-fashion", lighting: "dramatic directional", contrast: "high", saturation: "rich" },
    composition: { visualHierarchy: "photo full-bleed dominant", readingDirection: "top-down", whitespace: "low (within photo)", balance: "bold centered", imageScale: "full" },
    subjectTreatment: { people: "editorial pose", product: "styled", environment: "studio/location" },
    textTreatment: { placement: "top text over photo", overlay: "top gradient for legibility", gradient: "top", cardVariant: "photo-full-top-text" },
    decorativeElements: ["top scrim"], shapeLanguage: "sharp",
    consistencyRules: ["every frame full-bleed photo", "same top-headline treatment", "same dramatic light"],
    recommendedFor: ["fashion", "editorial", "launch"], avoid: ["pastel cute", "heavy cards"],
    frameRoles: { hero: "全出血大片", secondary: "造型細節", supporting: "配件特寫", closing: "品牌收尾" },
  },

  // ── D. Social / Conversation ────────────────────────────────────
  {
    id: "chat-bubble-social", name: "Chat Bubble Social", category: "social_conversation",
    description: "對話泡泡、聊天 UI、社群互動感。",
    visualConcept: "像聊天訊息的社群感，圓角對話框＋反應。",
    colorSystem: { primary: "friendly neutral", secondary: "chat-grey", accent: "brand bubble color", background: "light chat bg" },
    typography: { hierarchy: "conversational lines", headlineStyle: "friendly rounded sans", bodyStyle: "chat-size sans", labelStyle: "reaction tag", alignment: "left (chat)" },
    imageTreatment: { photographyStyle: "candid social snapshot", lighting: "natural casual", contrast: "medium", saturation: "friendly" },
    composition: { visualHierarchy: "bubbles guide reading", readingDirection: "top-down chat flow", whitespace: "medium", balance: "left-right bubble alternation", imageScale: "medium" },
    subjectTreatment: { people: "relatable, expressive", product: "mentioned in bubble", environment: "everyday" },
    textTreatment: { placement: "speech bubbles on photo", overlay: "rounded chat bubble", textBox: "rounded speech bubble", badge: "reaction icon", cardVariant: "speech-bubble-price" },
    decorativeElements: ["speech bubbles", "reaction icons", "rounded chat frames"], shapeLanguage: "very rounded (chat)",
    consistencyRules: ["same bubble style across frames", "same friendly palette", "consistent chat-UI language"],
    recommendedFor: ["testimonial", "promotion", "lifestyle", "product"], avoid: ["formal serif", "editorial coldness"],
    frameRoles: { hero: "開場對話＋人物", secondary: "產品提及泡泡", supporting: "反應/評論", closing: "行動泡泡" },
  },

  // ── E. Gradient / Overlay ───────────────────────────────────────
  {
    id: "portrait-gradient", name: "Portrait Gradient", category: "gradient_overlay",
    description: "人物大圖＋漸變覆蓋，文字疊在漸變區。",
    visualConcept: "人像主導，色彩漸變壓底/側，文字在漸變上。",
    colorSystem: { primary: "brand gradient duo", secondary: "deep tone", accent: "bright highlight", background: "gradient over portrait", gradient: "brand-color diagonal fade" },
    typography: { hierarchy: "bold headline on gradient", headlineStyle: "bold sans", bodyStyle: "medium", labelStyle: "pill", alignment: "bottom-left" },
    imageTreatment: { photographyStyle: "portrait", lighting: "soft key light", contrast: "medium", saturation: "rich" },
    composition: { visualHierarchy: "portrait dominant, text in gradient", readingDirection: "bottom-up", whitespace: "low", balance: "portrait-weighted", imageScale: "large portrait" },
    subjectTreatment: { people: "portrait, prominent", product: "held near face", environment: "simple, colored" },
    textTreatment: { placement: "bottom over gradient", overlay: "strong bottom/side gradient", gradient: "diagonal brand gradient", cardVariant: "gradient-bottom" },
    decorativeElements: ["color gradient wash"], shapeLanguage: "soft",
    consistencyRules: ["same gradient direction & colors all frames", "same portrait light", "text always on gradient"],
    recommendedFor: ["beauty", "launch", "promotion", "lifestyle"], avoid: ["flat white minimal", "no-overlay"],
    frameRoles: { hero: "人像＋漸變大標", secondary: "產品近臉", supporting: "細節漸變", closing: "CTA 漸變" },
  },

  // ── F. Product / E-commerce ─────────────────────────────────────
  {
    id: "product-hero-commerce", name: "Product Hero Commerce", category: "product_ecom",
    description: "產品主視覺、資訊標籤、商業導購感。",
    visualConcept: "產品英雄，清楚賣點標籤、導購力強。",
    colorSystem: { primary: "clean commercial", secondary: "neutral", accent: "strong CTA color", background: "clean studio / soft color" },
    typography: { hierarchy: "product name + benefit tags", headlineStyle: "bold commercial sans", bodyStyle: "clear", labelStyle: "benefit chip", alignment: "center/left" },
    imageTreatment: { photographyStyle: "clean commercial product", lighting: "bright studio", contrast: "medium-high", saturation: "vivid, true" },
    composition: { visualHierarchy: "product dominant + info", readingDirection: "center-out", whitespace: "medium", balance: "product-centered", imageScale: "large product" },
    subjectTreatment: { people: "optional hand model", product: "hero, crisp, centered", environment: "clean studio/gradient" },
    textTreatment: { placement: "badge straddling image edge", overlay: "info card", badge: "benefit badge", cardVariant: "card-badge-straddle" },
    decorativeElements: ["benefit chips", "badge"], shapeLanguage: "medium rounding",
    consistencyRules: ["same studio light every frame", "same badge/chip language", "product always crisp hero"],
    recommendedFor: ["product", "promotion", "launch"], avoid: ["moody dark", "messy lifestyle"],
    frameRoles: { hero: "產品主視覺", secondary: "產品特寫", supporting: "賣點標籤", closing: "導購 CTA" },
  },
  {
    id: "product-benefit-cards", name: "Product + Benefit Cards", category: "product_ecom",
    description: "產品＋功效卡片、價格帶，資訊清楚。",
    visualConcept: "產品＋一格格功效/價格卡，資訊型導購。",
    colorSystem: { primary: "clean neutral", secondary: "card grey", accent: "price/CTA accent", background: "light" },
    typography: { hierarchy: "product + benefit list + price", headlineStyle: "bold", bodyStyle: "benefit copy", labelStyle: "price label", alignment: "left" },
    imageTreatment: { photographyStyle: "product with soft context", lighting: "bright even", contrast: "medium", saturation: "true" },
    composition: { visualHierarchy: "product + info cards", readingDirection: "top-down list", whitespace: "medium", balance: "structured", imageScale: "medium-large" },
    subjectTreatment: { people: "optional", product: "clear, benefit-tagged", environment: "clean" },
    textTreatment: { placement: "bottom price card", overlay: "info card bottom", textBox: "benefit card", badge: "price", cardVariant: "card-price-bottom" },
    decorativeElements: ["benefit cards", "price tag"], shapeLanguage: "medium rounding",
    consistencyRules: ["same card & price language across frames", "same clean light", "same accent"],
    recommendedFor: ["product", "promotion"], avoid: ["editorial void", "no-info minimal"],
    frameRoles: { hero: "產品＋主賣點", secondary: "功效卡", supporting: "細節卡", closing: "價格/CTA 卡" },
  },

  // ── G. Beauty / Wellness ────────────────────────────────────────
  {
    id: "clinical-beauty", name: "Clinical Beauty", category: "beauty_wellness",
    description: "醫美/皮膚科乾淨感，冷靜、專業、可信。",
    visualConcept: "臨床潔淨美感，白＋冷藍、精準、專業。",
    colorSystem: { primary: "clinical white", secondary: "cool light blue", accent: "precise brand blue", background: "clean white/cool" },
    typography: { hierarchy: "precise headline + fine label", headlineStyle: "clean modern sans", bodyStyle: "fine", labelStyle: "small uppercase label", alignment: "left/center" },
    imageTreatment: { photographyStyle: "clean clinical/skin close", lighting: "even soft clinical", contrast: "medium", saturation: "cool, restrained" },
    composition: { visualHierarchy: "clean, precise", readingDirection: "top-down", whitespace: "high", balance: "orderly", imageScale: "medium-large" },
    subjectTreatment: { people: "clear skin close-ups", product: "clinical, precise", environment: "clean white" },
    textTreatment: { placement: "minimal top label", overlay: "subtle", badge: "small label", cardVariant: "minimal-top-label-card" },
    decorativeElements: ["thin precise line", "small icon"], shapeLanguage: "slightly rounded / precise",
    consistencyRules: ["same cool clinical palette", "same precise labels", "same even light"],
    recommendedFor: ["medical", "beauty", "wellness"], avoid: ["warm messy", "playful"],
    frameRoles: { hero: "潔淨主圖＋標", secondary: "肌膚/產品特寫", supporting: "成分/數據", closing: "專業收尾" },
  },
  {
    id: "spa-calm", name: "Spa Calm", category: "beauty_wellness",
    description: "SPA 療癒、寧靜、自然禪意。",
    visualConcept: "寧靜療癒，柔綠/石色、水/植物、呼吸感。",
    colorSystem: { primary: "sage / stone", secondary: "soft green", accent: "muted gold", background: "calm neutral" },
    typography: { hierarchy: "gentle headline + caption", headlineStyle: "light serif", bodyStyle: "light", labelStyle: "pill", alignment: "center" },
    imageTreatment: { photographyStyle: "spa/wellness still", lighting: "soft diffused", contrast: "low", saturation: "muted natural" },
    composition: { visualHierarchy: "calm balanced", readingDirection: "center-out", whitespace: "high", balance: "symmetric calm", imageScale: "medium" },
    subjectTreatment: { people: "relaxed", product: "with botanicals/water", environment: "spa, stones, plants" },
    textTreatment: { placement: "caption pill", overlay: "subtle", caption: "gentle", cardVariant: "photo-caption-pill" },
    decorativeElements: ["botanical accent", "soft pill"], shapeLanguage: "rounded",
    consistencyRules: ["same sage/stone palette", "same soft light", "same pill caption"],
    recommendedFor: ["wellness", "beauty"], avoid: ["high energy", "commercial hard-sell"],
    frameRoles: { hero: "療癒主圖", secondary: "產品＋植物", supporting: "質地細節", closing: "寧靜收束" },
  },

  // ── H. Collage / Scrapbook ──────────────────────────────────────
  {
    id: "polaroid-collage", name: "Polaroid Collage", category: "collage_scrapbook",
    description: "拍立得、手作拼貼、隨性真實感。",
    visualConcept: "拍立得白框＋隨性拼貼，手寫感、真實回憶。",
    colorSystem: { primary: "warm film neutral", secondary: "paper cream", accent: "handwritten ink", background: "paper/board" },
    typography: { hierarchy: "handwritten caption + label", headlineStyle: "casual/handwritten", bodyStyle: "casual", labelStyle: "corner label", alignment: "varied casual" },
    imageTreatment: { photographyStyle: "film/polaroid snapshot", lighting: "natural candid", contrast: "medium", saturation: "warm film", grain: "film grain" },
    composition: { visualHierarchy: "scattered but intentional", readingDirection: "scan/scatter", whitespace: "medium", balance: "playful overlap", imageScale: "varied" },
    subjectTreatment: { people: "candid memories", product: "casually placed", environment: "everyday" },
    textTreatment: { placement: "corner label/handwritten", overlay: "white polaroid border", textBox: "polaroid caption strip", cardVariant: "corner-label-card" },
    decorativeElements: ["polaroid frame", "tape", "handwriting"], shapeLanguage: "slight rotation, white borders",
    consistencyRules: ["same film tone across frames", "same polaroid border language", "same handwriting accent"],
    recommendedFor: ["lifestyle", "travel", "testimonial"], avoid: ["clinical", "corporate"],
    frameRoles: { hero: "大拍立得主圖", secondary: "小拍立得細節", supporting: "貼紙小圖", closing: "手寫收尾" },
  },

  // ── I. Cinematic / Storytelling ─────────────────────────────────
  {
    id: "cinematic-story", name: "Cinematic Story", category: "cinematic_story",
    description: "電影感、寬幅、戲劇光影、敘事。",
    visualConcept: "電影劇照感，寬幅黑邊、戲劇光、字幕式文字。",
    colorSystem: { primary: "cinematic teal-orange", secondary: "deep shadow", accent: "warm highlight", background: "letterboxed dark" },
    typography: { hierarchy: "subtitle-style caption", headlineStyle: "cinematic serif/sans", bodyStyle: "subtitle caption", labelStyle: "small", alignment: "bottom center (subtitle)" },
    imageTreatment: { photographyStyle: "cinematic still", lighting: "dramatic directional, deep shadows", contrast: "high", saturation: "graded (teal/orange)", grain: "cinematic grain" },
    composition: { visualHierarchy: "scene-led, wide", readingDirection: "sequential (story)", whitespace: "letterbox bars", balance: "cinematic framing", imageScale: "wide full-bleed" },
    subjectTreatment: { people: "in-scene, story moment", product: "as story prop", environment: "atmospheric" },
    textTreatment: { placement: "bottom subtitle over photo", overlay: "top+bottom scrim", gradient: "letterbox", cardVariant: "photo-full-top-text" },
    decorativeElements: ["letterbox bars", "subtitle"], shapeLanguage: "sharp",
    consistencyRules: ["same color grade across frames", "same letterbox & subtitle", "same dramatic light"],
    recommendedFor: ["travel", "launch", "editorial", "lifestyle"], avoid: ["bright pastel", "cute cards"],
    frameRoles: { hero: "開場劇照", secondary: "劇情推進", supporting: "細節鏡頭", closing: "收尾字幕" },
  },

  // ── J. Information / Educational ─────────────────────────────────
  {
    id: "step-by-step", name: "Step by Step", category: "info_educational",
    description: "步驟教學、編號、清楚流程。",
    visualConcept: "教學步驟，明確編號標籤、乾淨、易讀。",
    colorSystem: { primary: "clean neutral", secondary: "step accent", accent: "number highlight", background: "light" },
    typography: { hierarchy: "step number + instruction", headlineStyle: "bold step title", bodyStyle: "clear instruction", labelStyle: "STEP tab", alignment: "left" },
    imageTreatment: { photographyStyle: "clear demonstrative", lighting: "bright even", contrast: "medium", saturation: "true" },
    composition: { visualHierarchy: "number-led per frame", readingDirection: "sequential steps", whitespace: "medium", balance: "structured", imageScale: "medium" },
    subjectTreatment: { people: "hands demonstrating", product: "in use per step", environment: "clean" },
    textTreatment: { placement: "step tab + caption", overlay: "tab card", textBox: "step tab", badge: "STEP n", cardVariant: "ribbon-tab-card" },
    decorativeElements: ["numbered tab", "progress hint"], shapeLanguage: "medium rounding",
    consistencyRules: ["same STEP tab style & numbering", "same bright light", "same accent per set"],
    recommendedFor: ["tutorial", "before_after", "product"], avoid: ["moody editorial", "no-text"],
    frameRoles: { hero: "STEP 1 開場", secondary: "STEP 2/3", supporting: "細節步驟", closing: "完成/成果" },
  },
  {
    id: "before-after-clean", name: "Before / After Clean", category: "info_educational",
    description: "前後對比、清楚標記、可信。",
    visualConcept: "乾淨前後對比，一致框、明確 Before/After 標。",
    colorSystem: { primary: "clean neutral", secondary: "grey", accent: "result accent", background: "white" },
    typography: { hierarchy: "before/after label + caption", headlineStyle: "bold", bodyStyle: "small", labelStyle: "corner badge", alignment: "top" },
    imageTreatment: { photographyStyle: "consistent comparison", lighting: "identical even light", contrast: "medium", saturation: "true" },
    composition: { visualHierarchy: "paired comparison", readingDirection: "left-right / before-after", whitespace: "medium", balance: "mirrored", imageScale: "equal" },
    subjectTreatment: { people: "same subject before/after", product: "cause of change", environment: "identical" },
    textTreatment: { placement: "corner before/after badge", overlay: "badge", badge: "Before / After", cardVariant: "badge-top-left" },
    decorativeElements: ["before/after badge", "divider"], shapeLanguage: "medium",
    consistencyRules: ["identical framing & light before vs after", "same badge language", "same accent"],
    recommendedFor: ["before_after", "beauty", "medical", "tutorial"], avoid: ["inconsistent light", "heavy decoration"],
    frameRoles: { hero: "對比主圖", secondary: "細節對比", supporting: "數據/說明", closing: "成果收尾" },
  },

  // ── K. Promotional / Campaign ───────────────────────────────────
  {
    id: "sale-campaign", name: "Sale Campaign", category: "promotional_campaign",
    description: "促銷檔期、斜緞帶、高對比、急迫感。",
    visualConcept: "促銷力，斜角緞帶＋大字折扣、高能量。",
    colorSystem: { primary: "high-energy brand", secondary: "contrast", accent: "SALE red/gold", background: "bold color block" },
    typography: { hierarchy: "huge discount + terms", headlineStyle: "heavy impact", bodyStyle: "bold", labelStyle: "ribbon", alignment: "center" },
    imageTreatment: { photographyStyle: "punchy product/lifestyle", lighting: "bright punchy", contrast: "high", saturation: "vivid" },
    composition: { visualHierarchy: "offer dominant", readingDirection: "center burst", whitespace: "low", balance: "bold central", imageScale: "medium" },
    subjectTreatment: { people: "energetic", product: "prominent with offer", environment: "bold color" },
    textTreatment: { placement: "diagonal ribbon + big number", overlay: "diagonal ribbon", badge: "SALE ribbon", cardVariant: "diagonal-ribbon-card" },
    decorativeElements: ["diagonal ribbon", "burst", "big % number"], shapeLanguage: "bold angular",
    consistencyRules: ["same ribbon & SALE color across frames", "same high-energy light", "consistent offer language"],
    recommendedFor: ["promotion", "seasonal", "launch"], avoid: ["quiet minimal", "editorial calm"],
    frameRoles: { hero: "折扣主視覺", secondary: "商品＋價", supporting: "條件說明", closing: "CTA 緞帶" },
  },
  {
    id: "limited-offer", name: "Limited Offer", category: "promotional_campaign",
    description: "限時優惠、對話泡泡價格、明確 CTA。",
    visualConcept: "限時感，價格泡泡＋倒數，導購明確。",
    colorSystem: { primary: "urgent brand", secondary: "neutral", accent: "price highlight", background: "clean with accent" },
    typography: { hierarchy: "offer + deadline + CTA", headlineStyle: "bold", bodyStyle: "clear", labelStyle: "price bubble", alignment: "center/left" },
    imageTreatment: { photographyStyle: "clean product", lighting: "bright", contrast: "medium-high", saturation: "vivid" },
    composition: { visualHierarchy: "price + CTA dominant", readingDirection: "center-out", whitespace: "medium", balance: "focused", imageScale: "medium" },
    subjectTreatment: { people: "optional", product: "clear with price", environment: "clean" },
    textTreatment: { placement: "price speech bubble", overlay: "bubble", badge: "限時", textBox: "price bubble", cardVariant: "speech-bubble-price" },
    decorativeElements: ["price bubble", "countdown hint"], shapeLanguage: "rounded",
    consistencyRules: ["same price bubble style", "same urgent accent", "consistent CTA language"],
    recommendedFor: ["promotion", "seasonal"], avoid: ["editorial", "moody"],
    frameRoles: { hero: "優惠主視覺", secondary: "商品＋價泡泡", supporting: "條件", closing: "立即行動" },
  },

  // ── Special ─────────────────────────────────────────────────────
  {
    id: "luxury-black", name: "Luxury Black", category: "special",
    description: "精品黑金、極簡奢華、高級感。",
    visualConcept: "深黑＋金，極簡奢華，精品廣告感。",
    colorSystem: { primary: "deep black", secondary: "charcoal", accent: "gold", background: "black" },
    typography: { hierarchy: "fine luxury headline", headlineStyle: "thin elegant serif, wide spacing", bodyStyle: "fine", labelStyle: "gold micro-label", alignment: "center" },
    imageTreatment: { photographyStyle: "luxury product/portrait", lighting: "low-key, single sculpted light", contrast: "high", saturation: "restrained, rich" },
    composition: { visualHierarchy: "product/subject glows in dark", readingDirection: "center-out", whitespace: "high (black void)", balance: "centered", imageScale: "medium" },
    subjectTreatment: { people: "elegant", product: "spotlighted on black", environment: "dark void" },
    textTreatment: { placement: "bottom banner", overlay: "black banner", gradient: "bottom", cardVariant: "banner-bottom" },
    decorativeElements: ["thin gold line"], shapeLanguage: "sharp / minimal",
    consistencyRules: ["black background every frame", "same gold accent & thin serif", "same low-key light"],
    recommendedFor: ["launch", "beauty", "fashion", "promotion"], avoid: ["bright airy", "playful"],
    frameRoles: { hero: "黑金主視覺", secondary: "產品聚光", supporting: "細節", closing: "金線收尾" },
  },
];
